replicaCount: 1

image:
  registry: asia-south1-docker.pkg.dev
  project: ""  # set your GCP project ID
  repository: github-actions-demo/github-actions-demo
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
