replicaCount: 1

image:
  registry: asia-south1-docker.pkg.dev
  project: "jenkins-demo-501207"  # set your GCP project ID
  repository: github-actions-demo/github-actions-demo
  tag: b163a3a4f5b18e23f5de23ab98b0b1087abc0230
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
